# Generated by Django 4.1.1 on 2022-09-27 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('E', 'English'), ('H', 'Hindi'), ('G', 'Gujrati')], default='E', max_length=2)),
                ('expertise', models.CharField(max_length=100)),
                ('fee', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('year_of_expierence', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
