# Generated by Django 4.1.1 on 2022-09-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Gujrati', 'Gujrati')], default='English', max_length=20),
        ),
    ]
