# Generated by Django 4.1.1 on 2022-09-27 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_alter_doctor_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depressiontest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('above_30_age', models.IntegerField()),
                ('city', models.IntegerField()),
                ('sadness_momentarily', models.IntegerField()),
                ('time_of_day', models.IntegerField()),
                ('changes_in_life', models.IntegerField()),
                ('activities', models.IntegerField()),
                ('supported', models.IntegerField()),
                ('mean_something', models.IntegerField()),
                ('mental_health_condition', models.IntegerField()),
                ('leave', models.IntegerField()),
                ('substance_abuse', models.IntegerField()),
                ('therepy', models.IntegerField()),
                ('concentrating', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
