# Generated by Django 4.1.1 on 2022-10-01 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0004_depressiontest_prediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diseasetest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbness', models.IntegerField()),
                ('headache', models.IntegerField()),
                ('vision_changes', models.IntegerField()),
                ('breathing', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('body_sweating', models.IntegerField()),
                ('thought', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('feeling', models.IntegerField()),
                ('frustrated', models.IntegerField()),
                ('nightmares', models.IntegerField()),
                ('traumetic', models.IntegerField()),
                ('shouted_fight', models.IntegerField()),
                ('social', models.IntegerField()),
                ('hyper', models.IntegerField()),
                ('prediction', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
