# Generated by Django 4.1.1 on 2022-10-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_diseasetest_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
