# Generated by Django 4.1.1 on 2022-10-14 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_desease_user_alter_doctor_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desease',
            name='user',
        ),
    ]
