# Generated by Django 4.1.1 on 2022-10-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_remove_desease_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasetest',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
