# Generated by Django 4.1.1 on 2022-10-14 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_diseasetest_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseasetest',
            name='description',
        ),
    ]
