# Generated by Django 4.1.1 on 2023-02-10 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0019_userprofile_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField()),
                ('Gender', models.IntegerField()),
                ('self_employed', models.IntegerField()),
                ('family_history', models.IntegerField()),
                ('work_interfere', models.IntegerField()),
                ('no_employees', models.IntegerField()),
                ('remote_work', models.IntegerField()),
                ('tech_company', models.IntegerField()),
                ('benefits', models.IntegerField()),
                ('care_options', models.IntegerField()),
                ('wellness_program', models.IntegerField()),
                ('seek_help', models.IntegerField()),
                ('anonymity', models.IntegerField()),
                ('leave', models.IntegerField()),
                ('mental_health_consequence', models.IntegerField()),
                ('phys_health_consequence', models.IntegerField()),
                ('coworkers', models.IntegerField()),
                ('supervisor', models.IntegerField()),
                ('phys_health_interview', models.IntegerField()),
                ('mental_vs_physical', models.IntegerField()),
                ('MentalHealthProblem', models.IntegerField()),
                ('prediction', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
